"""ffscan step 3: generate the swtomotv dataset YAMLs + the job manifest for the r/lambda scan.

One YAML per (net, measure, dx, min r/lambda X): pick_files -> the ffscan threshold tables,
output_root -> .../production/ffscan/uni_{measure}_ff{X}_dx{dx} (the dirname carries the
threshold, per the scan's provenance requirement). Grid pairs (coarse/fine):
riehen 0.5/0.2, aargau 1.0/0.5, hautesorne 1.0/0.5 km; LC = 3*dx (production convention).

riehen/aargau YAMLs additionally get the dem + GK500 tecto layers (copied from styled_maps.py's
per-net overrides) so `swtomotv produce --topo` / `aniso` can run — the historical unified YAMLs
lacked them because topo/aniso had only ever been run on hautesorne.

Writes {inputs}/ffscan/yamls/*.yaml and {EHM}/ffscan_logs/ffscan_manifest.json.
"""
import itertools
import json
import os

EHM = "/Users/genevievesavard/Codes/extract_higher_modes/Projects"
GK500_V14 = ("/Users/genevievesavard/Data/hautesorne/GIS/GK-500-V-4/GK500_V1_4_FR/"
             "Shapes_WGS84")
THRESHOLDS = [1.0, 1.5, 2.0, 2.5, 3.0]

TECTO = f"""tecto_layers:
  - path: {GK500_V14}/LI_Accident_tecto_wgs84.shp
    kind: fault
    where: "Type.str.contains('Faille')"
  - path: {GK500_V14}/LI_Accident_tecto_wgs84.shp
    kind: thrust
    where: "Type.str.contains('Chevauchement')"
  - path: {GK500_V14}/LI_Axes_de_struct_wgs84.shp
    kind: anticline
"""

HS_REFMODEL = """# Lanza et al. (2022) St-Ursanne model (A8 mode-check QC only; TV prior unaffected)
reference_model:
  - [220,  4335.00, 2477.14, 2750]
  - [390,  3134.00, 1790.86, 2150]
  - [60,   3163.00, 1807.43, 2850]
  - [220,  3135.00, 1791.43, 2750]
  - [330,  4494.00, 2568.00, 2250]
  - [440,  3927.00, 2310.00, 2250]
  - [8340, 6000.00, 3500.00, 2600]
  - [5000, 6100.00, 3570.00, 2700]
  - [5000, 6200.00, 3630.00, 2700]
  - [5000, 6300.00, 3690.00, 2800]
  - [5000, 6531.58, 3768.22, 2885.98]
  - [0,    8113.69, 4517.04, 3347.69]
"""

NETS = {
    "riehen": dict(
        bounds="[47.500977, 47.666447, 7.534873, 7.777094]",
        waves=("fund", "overtone", "love"),
        grids=(0.5, 0.2),
        dem=f"""dem:
  kind: geotiff
  path: {EHM}/riehen/tomo/dem/output_SRTMGL1.tif
  crs: EPSG:4326
""",
        extra=TECTO),
    "aargau": dict(
        bounds="[47.377852, 47.617948, 8.052090, 8.398219]",
        waves=("fund", "overtone", "love"),
        grids=(1.0, 0.5),
        dem=f"""dem:
  kind: geotiff
  path: {EHM}/aargau/tomo/dem/N47E008.hgt
  crs: EPSG:4326
""",
        extra=TECTO),
    "hautesorne": dict(
        bounds="[47.237194, 47.464396, 6.945514, 7.491476]",
        waves=("fund", "overtone", "love", "love_ot"),
        grids=(1.0, 0.5),
        dem=f"""dem:
  kind: arcgrid
  path: /Users/genevievesavard/Data/hautesorne/GIS/ASCII_GRID_1part/swiss_dem_hautesorne_lv03.asc
  crs: EPSG:21781
""",
        extra=HS_REFMODEL + TECTO),
}

jobs = []
for net, cfg in NETS.items():
    inputs = f"{EHM}/{net}/tomo/1_velocity_maps/inputs"
    ydir = f"{inputs}/ffscan/yamls"
    os.makedirs(ydir, exist_ok=True)
    for measure, dx, X in itertools.product(("group", "phase"), cfg["grids"], THRESHOLDS):
        tag = "_phase" if measure == "phase" else ""
        run = f"uni_{measure}_ff{X:.1f}_dx{dx:g}"
        output_root = f"{EHM}/{net}/tomo/1_velocity_maps/production/ffscan/{run}"
        picks = "\n".join(
            f"  {w}:{' ' * (9 - len(w))}{inputs}/ffscan/picks_{w}_uni{tag}_ff{X:.1f}.csv"
            for w in cfg["waves"])
        filters = "\n".join(f"  {w}:{' ' * (9 - len(w))}[100.0, 1]" for w in cfg["waves"])
        twostep = "\n".join(f"  {w}: false" for w in cfg["waves"])
        ypath = f"{ydir}/{net}_{run}.yaml"
        with open(ypath, "w") as fh:
            fh.write(f"""# ffscan arm: {net} {measure} min r/lambda {X:.1f} dx {dx:g} km
# generated by ffscan_make_yamls.py -- edit the generator, not this file
name: {net}_ffscan_{measure}_ff{X:.1f}_dx{dx:g}
pick_files:
{picks}
station_file: {inputs}/stations.csv
output_root: {output_root}
bounds: {cfg['bounds']}
dx_km: {dx}
filters:
{filters}
two_step:
{twostep}
columns: {{}}
# periods are the picker's native CWT scale ladder (uneven, ~5.95% spacing): 1 decimal
# would make neighbouring rungs share a cache file and silently overwrite each other
period_decimals: 3
{cfg['dem']}{cfg['extra']}""")
        jobs.append(dict(net=net, measure=measure, dx=dx, ff=X, run=run,
                         yaml=ypath, output_root=output_root,
                         waves=list(cfg["waves"]), lc=round(3 * dx, 2),
                         fine=(dx == min(cfg["grids"]))))

mpath = f"{EHM}/../ffscan_logs/ffscan_manifest.json"
os.makedirs(os.path.dirname(mpath), exist_ok=True)
with open(mpath, "w") as fh:
    json.dump(jobs, fh, indent=1)
print(f"{len(jobs)} arms -> {os.path.normpath(mpath)}")
