"""Synthetic VTI validation gates for the radial-anisotropy inversion (plan §5 gates 1+2).

The ONLY legitimate null: a model where gamma(z) is known BY CONSTRUCTION. Real cells cannot
serve as nulls -- an isotropic model fitting adequately says nothing about whether gamma=0 is
true (that non-sequitur was removed from the plan).

Forward (the two-isotropic-forwards approximation the inversion itself uses, and the community
standard / Esteve et al. AJES26_08):
    Rayleigh R0/R1  <- disba on the Vsv model
    Love     L0     <- disba on the Vsh model = Vsv * (1 + gamma)
group AND phase, on the SAME period grid + sigma as a REAL cell (so the test inherits the real
band and noise level rather than an optimistic one).

Cases:
  null   : gamma(z) = 0 everywhere        -> PASS if the posterior keeps gamma dead.
           This also CALIBRATES P(gamma!=0): whatever P the sampler reports here IS the null
           distribution (P is spike-and-slab occupancy, meaningless without its prior/null level).
  vti    : gamma = 0 above 1 km, +0.10 below   -> PASS if recovered where Love kernels live.
  neg    : gamma = -0.10 above 1.5 km, 0 below -> the sign the real data keeps preferring;
           tests whether a NEGATIVE gamma is recoverable or just absorbs bias.
  leak   : gamma(z) = 0 everywhere AND the "Love" curve is generated by the RAYLEIGH forward --
           a perfect simulation of R0 leaking onto TT (Riehen, confirmed 2026-07-15: the picked
           Love branch sits +1.7% from R0, below the ~+9% isotropic Love floor that no layered
           elastic medium can breach).  The truth is ISOTROPIC, so any gamma the sampler reports
           here is manufactured purely by the contamination.  PASS = gamma stays dead.  FAIL
           (expected) = a large structured gamma with high P(gamma!=0), proving the real Riehen
           gamma is a picking artifact and NOT an evaporite decollement.

Usage (bayesbay env; shells out to the bayhunter env):
  PYTHONPATH=~/Codes/NoisePy-ant python synth_radial_gate.py --case null --measure both \
      --template-npz <a real wells_measure npz>  --outdir DIR \
      --n-chains 16 --iter-burnin 160000 --iter-main 80000 \
      --bayhunter-python ... --bayhunter-runner run_bayhunter_cell.py
"""
import argparse
import json
import os
import subprocess

import numpy as np

# --- truth models: (thickness_km, Vsv_kms) + gamma(z) rule -------------------------------------
TRUTH_TH = np.array([0.3, 0.5, 0.7, 1.0, 1.5, 2.0, 100.0])
TRUTH_VSV = np.array([0.9, 1.3, 1.7, 2.1, 2.5, 2.8, 3.2])


def gamma_truth(case, zmid):
    g = np.zeros(len(zmid))
    if case == "vti":
        g[zmid >= 1.0] = 0.10
    elif case == "neg":
        g[zmid < 1.5] = -0.10
    # "leak" and "null" are both gamma == 0; they differ only in how the Love DATA is built.
    return g


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--case", required=True, choices=("null", "vti", "neg", "leak"))
    ap.add_argument("--measure", default="both", choices=("group", "phase", "both"))
    ap.add_argument("--template-npz", required=True,
                    help="a real run's npz: donates the period grids + sigmas per wave/measure")
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--depth-max", type=float, default=6.0)
    ap.add_argument("--vs-min", type=float, default=0.3)
    ap.add_argument("--vs-max", type=float, default=4.0)
    ap.add_argument("--radial-prior", default="-0.35,0.35")
    ap.add_argument("--vpvs-range", default="1.5,3.5")
    ap.add_argument("--n-chains", type=int, default=16)
    ap.add_argument("--iter-burnin", type=int, default=160000)
    ap.add_argument("--iter-main", type=int, default=80000)
    ap.add_argument("--maxmodels", type=int, default=20000)
    ap.add_argument("--pred-nsub", type=int, default=200)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--bayhunter-python", required=True)
    ap.add_argument("--bayhunter-runner", required=True)
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    from disba import GroupDispersion, PhaseDispersion
    zmid = np.cumsum(TRUTH_TH) - TRUTH_TH / 2.0
    g = gamma_truth(args.case, zmid)
    vsv = TRUTH_VSV.copy()
    vsh = vsv * (1.0 + g)
    vp = 1.73 * vsv                       # vp/rho tied to Vsv (SH is Vp-insensitive)
    rho = 0.32 * vp + 0.77
    np.savez(os.path.join(args.outdir, "truth.npz"), thickness=TRUTH_TH, vsv=vsv, vsh=vsh,
             gamma=g, zmid=zmid, case=args.case)

    # period grids + sigmas donated by a real cell -> the synthetic inherits the REAL band
    tpl = np.load(args.template_npz, allow_pickle=True)
    WAVE = {"fund": ("rayleigh", 0), "overtone": ("rayleigh", 1), "love": ("love", 0)}
    curves, curves_phase = {}, {}
    for key in tpl["waves"]:
        key = str(key)
        base = key.replace("_phase", "")
        meas = "phase" if key.endswith("_phase") else "group"
        if base not in WAVE:
            continue
        if args.measure != "both" and meas != args.measure:
            continue
        T = np.asarray(tpl[f"obsT_{key}"], float)
        S = np.asarray(tpl[f"obssig_{key}"], float)
        wtype, mode = WAVE[base]
        model_vs = vsh if wtype == "love" else vsv          # <-- the VTI forward
        if args.case == "leak" and wtype == "love":
            # R0 leaking onto TT: the "Love" channel actually carries the Rayleigh fundamental.
            # Keep the Love period grid + sigma (so the band/noise stay realistic) but compute
            # the RAYLEIGH fundamental on Vsv. Truth gamma is 0, so a gamma recovered from this
            # can only have been manufactured by the contamination.
            wtype, mode, model_vs = "rayleigh", 0, vsv
        Disp = GroupDispersion if meas == "group" else PhaseDispersion
        d = Disp(TRUTH_TH, vp, model_vs, rho)
        try:
            cp = d(np.sort(T), mode=mode, wave=wtype)
        except Exception as e:
            print(f"  {key}: forward failed ({e}); skipped"); continue
        Tv = np.asarray(cp.period, float); Vv = np.asarray(cp.velocity, float)
        idx = {round(float(t), 6): i for i, t in enumerate(Tv)}
        keep = [(t, s) for t, s in zip(T, S) if round(float(t), 6) in idx]
        if len(keep) < 4:
            print(f"  {key}: <4 periods survive the forward; skipped"); continue
        Tk = np.array([k[0] for k in keep]); Sk = np.array([k[1] for k in keep])
        Vk = np.array([Vv[idx[round(float(t), 6)]] for t in Tk])
        Vk = Vk + rng.normal(0.0, Sk)                        # realistic noise
        fp = os.path.join(args.outdir, f"disp_{key}.txt")
        np.savetxt(fp, np.column_stack([Tk, Vk, Sk]), fmt="%.6f")
        (curves_phase if meas == "phase" else curves)[base] = fp
        print(f"  {key:16s}: {len(Tk):2d} pts T {Tk.min():.1f}-{Tk.max():.1f}s "
              f"v {Vk.min():.2f}-{Vk.max():.2f} sig~{np.median(Sk):.3f}")

    if args.measure == "phase":
        curves, curves_phase = curves_phase, {}
    if not curves:
        raise SystemExit("no synthetic curves built")

    cfg = dict(measure=("phase" if args.measure == "phase" else "group"),
               curves=curves, out_npz=os.path.join(args.outdir, f"synth_{args.case}.npz"),
               savepath=os.path.join(args.outdir, "bh_results"),
               cell=[0, 0, float("nan"), float("nan")], depth_max=args.depth_max,
               vs_bounds=[args.vs_min, args.vs_max], n_layers=[1, 20], maxfrac=0.5,
               nchains=args.n_chains, iter_burnin=args.iter_burnin, iter_main=args.iter_main,
               maxmodels=args.maxmodels, pred_nsub=args.pred_nsub, save_ensemble=True,
               radial_anisotropy=True,
               radial_prior=[float(x) for x in args.radial_prior.split(",")],
               vpvs=[float(x) for x in args.vpvs_range.split(",")])
    if args.measure == "both" and curves_phase:
        cfg["curves_phase"] = curves_phase
    cfgp = os.path.join(args.outdir, "config.json")
    json.dump(cfg, open(cfgp, "w"))
    env = dict(os.environ, OBJC_DISABLE_INITIALIZE_FORK_SAFETY="YES",
               VECLIB_MAXIMUM_THREADS="1", OMP_NUM_THREADS="1",
               OPENBLAS_NUM_THREADS="1", MKL_NUM_THREADS="1")
    print(f"inverting synthetic case={args.case} measure={args.measure} ...", flush=True)
    subprocess.run([args.bayhunter_python, args.bayhunter_runner, cfgp], check=True, env=env)
    print("done ->", cfg["out_npz"])


if __name__ == "__main__":
    main()
