#!/usr/bin/env python3
"""Write RUN_LINEAGE.md into each network's tomo/1_velocity_maps/ folder.

Velocity-map runs accumulate as `tspws_<measure>_<cd>_dx<dx><tag>` directories, and the tag
alone does not say which pick tree fed the run, which Fresnel convention set LC, or which
masks were applied to the output. Those are the THREE axes on which runs are not comparable:

1. FRESNEL (found 2026-08-03). run_production computed the "first Fresnel half-width" as
   sqrt(lam*L/2) -- the FULL-wavelength detour, i.e. the second Fresnel zone. Yoshizawa &
   Kennett (2002, GJI 149, 440, eq 24) define the first zone by a lam/2 detour, giving
   sqrt(lam*L)/2; the old form was sqrt(2) larger. Every run before _prod2 carries it.

2. PICK-HISTOGRAM VEIL (disabled 2026-08-04). `--vplaus dens:0.02` hid map cells whose
   velocity fell outside the band where the pick histogram exceeds 2% of its peak. On Aargau
   it removed 111-144 northern cells per period, 100% of them one real geological unit
   (Plate-forme mesozoique epivarisque), flagged purely for being fast. Veiled values were
   preserved in `vel_hidden`, so affected runs are recoverable at plot time.

3. RESOLUTION RANK-CUT (set to 0 on 2026-08-05). `--res-drop-q 0.25` discarded the
   worst-resolved QUARTER of cells by rank, regardless of absolute resolution. res_diag is
   speckly cell-to-cell, so the discarded quarter was scattered: isolated holes inside
   well-imaged regions, ~33% of the footprint (371-455 cells/period on Aargau phase).

Facts that can be read from the maps themselves (LC range, se, cd_mode, vplaus, counts) are
read from them, not from a hand-maintained table, so the file cannot drift from what was
actually computed. Runs are found RECURSIVELY under tomo/1_velocity_maps/, so the generator
works on both the flat pre-2026-08-05 layout and the workflow layout that replaced it.

Usage:
  python write_run_lineage.py --projects <.../Projects> [--nets riehen aargau hautesorne]
"""
import argparse
import glob
import os
import re

import numpy as np

# tag -> (pick tree, description, fresnel family, masking)
CORR = "corrected"
LEGF = "legacy (sqrt2 too large)"
M_OLD = "veil off; res-drop-q 0.25"
M_VEIL = "veil dens:0.02 (hidden cells kept in vel_hidden); res-drop-q 0.25"
M_NONE = "no veil; res-drop-q 0 (coverage footprint only)"
TAGS = {
    "": ("inputs_tspws", "first ts-PWS production; LC = Fresnel(uncorrected) x 1.0",
         LEGF, M_OLD),
    "_lccov": ("inputs_tspws", "LC from ray coverage (smallest LC bridging sampling gaps)",
               LEGF, M_VEIL),
    "_lcinfl": ("inputs_tspws", "LC = 1/3 Fresnel 'influence zone' -- but on the UNCORRECTED "
                                "half-width, so 1.41x wider than Yoshizawa & Kennett",
                LEGF, M_VEIL),
    "_lcfix1": ("inputs_tspws", "LC fixed at 1.0 km for every period", LEGF, M_OLD),
    "_lc0.5": ("inputs_tspws", "LC = Fresnel(uncorrected) x 0.5", LEGF, M_OLD),
    "_histfilt": ("inputs_tspws_histfilt (hist2d p75 cull)",
                  "REJECTED experiment: 2D-histogram cell cull at p75 removes 56% of the "
                  "graben signal and whole period rungs; also crashed 2 scaled-Cd overtone "
                  "inversions", LEGF, M_VEIL),
    "_vbk2": ("vbounds_ksweep/k2", "SUPERSEDED partial output from a cancelled run "
                                   "(cluster only)", LEGF, M_VEIL),
    "_vbk3": ("vbounds_ksweep/k3", "SUPERSEDED partial output from a cancelled run "
                                   "(cluster only)", LEGF, M_VEIL),
    "_prod2_k2": ("vbounds_ksweep/k2", "production series 2: corrected Fresnel + vbounds "
                                       "k=2 cull -- superseded by prod3 (masking)",
                  CORR, M_VEIL),
    "_prod2_k3": ("vbounds_ksweep/k3", "production series 2: corrected Fresnel + vbounds "
                                       "k=3 cull -- superseded by prod3 (masking)",
                  CORR, M_VEIL),
    "_prod3_k2": ("vbounds_ksweep/k2", "production series 3: prod2 + all output masking "
                                       "removed. k=2 comparison run.", CORR, M_NONE),
    "_prod3_k3": ("vbounds_ksweep/k3", "production series 3: prod2 + all output masking "
                                       "removed. CURRENT RECOMMENDED RUN.", CORR, M_NONE),
}
RUN_RE = re.compile(r"^tspws_(group|phase)_(blanket|scaled|measured)_dx([0-9.]+)(.*)$")

HEADER = """# Velocity-map run lineage -- {net}

Generated by `scripts/picking/write_run_lineage.py`; do not hand-edit (re-run it instead).
Per-run fields below are read from the `map_T*.npz` themselves.

## The three axes on which runs are NOT comparable

**1. Fresnel convention** (fixed 2026-08-03). Pre-`_prod2` runs computed LC from
`sqrt(lam*L/2)` -- the full-wavelength detour, i.e. the *second* Fresnel zone --
**sqrt(2) larger** than the Yoshizawa & Kennett (2002, GJI 149, 440, eq 24) first zone
`sqrt(lam*L)/2` now in use. Legacy runs are not *wrong* (LC is a prior), but their LC differs
by sqrt(2) wherever the floor is not binding, and `_lcinfl` cannot be called "the Y&K
influence zone".

**2. Pick-histogram veil** (disabled 2026-08-04). `--vplaus dens:0.02` hid output cells
outside the band where the pick histogram exceeds 2% of peak. It removed 111-144 northern
Aargau cells/period -- 100% one real unit -- and bit hardest where picks are densest.
Veiled values survive in `vel_hidden`; current plotting merges them back.

**3. Resolution rank-cut** (set to 0 on 2026-08-05). `--res-drop-q 0.25` dropped the
worst-resolved quarter of cells BY RANK, producing scattered interior holes and costing
~33% of the imaged area. `_prod3_*` keeps every covered cell.

| family | Fresnel | masking | runs |
|---|---|---|---|
| current | corrected | none | {cur}
| corrected but masked | corrected | veil + rank-cut | {corrmask}
| legacy | sqrt(2) too large | varies (see per-tag) | {legacy}

## Runs on disk

"""


def summarize(run_dir):
    npz = sorted(glob.glob(os.path.join(run_dir, "production", "*", "map_T*.npz")))
    if not npz:
        return None
    waves = sorted({os.path.basename(os.path.dirname(f)) for f in npz})
    lcs, se, cdm, vpl = [], None, None, None
    for f in npz[:: max(1, len(npz) // 40)]:
        try:
            z = np.load(f)
        except Exception:
            continue
        lcs.append(float(z["LC"]))
        if se is None and "se" in z.files:
            se = float(z["se"])
        if cdm is None and "cd_mode" in z.files:
            cdm = str(z["cd_mode"])
        if vpl is None and "vplaus" in z.files:
            vpl = str(z["vplaus"])
    if not lcs:
        return None
    return dict(n=len(npz), waves=waves, lc_lo=min(lcs), lc_hi=max(lcs),
                se=se, cd=cdm, vplaus=vpl)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--projects", required=True)
    ap.add_argument("--nets", nargs="+", default=["riehen", "aargau", "hautesorne"])
    a = ap.parse_args()

    for net in a.nets:
        root = os.path.join(a.projects, net, "tomo", "1_velocity_maps")
        if not os.path.isdir(root):
            print("skip %s" % net)
            continue
        runs = sorted(d for d in glob.glob(os.path.join(root, "**", "tspws_*"),
                                           recursive=True)
                      if os.path.isdir(d) and RUN_RE.match(os.path.basename(d))
                      and not os.path.islink(d))
        by_tag = {}
        for r in runs:
            m = RUN_RE.match(os.path.basename(r))
            by_tag.setdefault(m.group(4), []).append(r)

        fam = lambda t: TAGS.get(t, ("?", "?", "?", "?"))[2]
        msk = lambda t: TAGS.get(t, ("?", "?", "?", "?"))[3]
        cur = [t for t in by_tag if fam(t) == CORR and msk(t) == M_NONE]
        cm = [t for t in by_tag if fam(t) == CORR and msk(t) != M_NONE]
        leg = [t for t in by_tag if fam(t) != CORR]
        fmt = lambda ts: ", ".join("`%s`" % (t or "(untagged)") for t in sorted(ts)) or "none"
        out = [HEADER.format(net=net, cur=fmt(cur), corrmask=fmt(cm), legacy=fmt(leg))]

        order = sorted(by_tag, key=lambda t: (fam(t) != CORR, msk(t) != M_NONE, t))
        for tag in order:
            picks, desc, family, masking = TAGS.get(
                tag, ("unknown", "undocumented tag", "unknown", "unknown"))
            out.append("### `%s`\n\n%s\n" % (tag or "(untagged)", desc))
            out.append("- picks: `%s`\n- Fresnel: %s\n- masking: %s\n"
                       % (picks, family, masking))
            rows = []
            for r in sorted(by_tag[tag]):
                rel = os.path.relpath(r, root)
                s = summarize(r)
                if s is None:
                    rows.append("| `%s` | *(no maps)* | | | | | |" % rel)
                    continue
                rows.append("| `%s` | %d | %s | %.2f-%.2f | %s | %s | %s |"
                            % (rel, s["n"], ",".join(s["waves"]), s["lc_lo"], s["lc_hi"],
                               ("%.3f" % s["se"]) if s["se"] is not None else "?",
                               s["cd"] or "?", s["vplaus"] or "off"))
            out.append("\n| run dir | maps | waves | LC range km | se | Cd | vplaus |\n"
                       "|---|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n\n")

        p = os.path.join(root, "RUN_LINEAGE.md")
        open(p, "w").write("".join(out))
        print("wrote %s  (%d tags, %d run dirs)" % (p, len(by_tag), len(runs)))


if __name__ == "__main__":
    main()
