#!/usr/bin/env python3
"""Derive the yggdrasil cluster configs from the local ones by rewriting paths only.

Generating rather than hand-copying keeps every picking/QC/export parameter bit-identical
to what was validated locally -- the only differences are filesystem paths and, for
Haute-Sorne, the stack method (its local config still says pws because it had no substacks
until the cluster copy appeared).

Writes into param_files/cluster/:
    modesep_<net>_tspws.yaml    picker parameters, stack_root -> the ts-PWS tree
    pipeline_<net>_tspws.yaml   pick/QC/export stages for run_pipeline.py

Re-run this whenever the cluster paths change (they live in env.sh too -- keep both in step).

Usage:
  python make_cluster_configs.py [--noisepy PATH] [--proj PATH] [--data PATH]
"""
import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PARAM = os.path.join(HERE, "..", "param_files")
OUT = os.path.join(PARAM, "cluster")

CDFF = "/srv/beegfs/scratch/shares/cdff"

# per-network: (local modesep template, cluster SOURCE substack root, station-code prefix)
NETS = {
    "riehen":     ("modesep_riehen_tspws.yaml",
                   CDFF + "/riehen/crosscorrelations/STACK_CHRI_normZ", "RI"),
    "aargau":     ("modesep_aargau_tspws.yaml",
                   CDFF + "/aargau/crosscorrelations/STACK_CHAA_normZ", "AA"),
    "hautesorne": ("modesep_hautesorne.yaml",
                   CDFF + "/hautesorne/STACK_coh", "SS"),
}
LOCAL_NOISEPY = "/Users/genevievesavard/Codes/NoisePy-ant"
LOCAL_PROJ = "/Users/genevievesavard/Codes/extract_higher_modes/Projects"
LOCAL_DATA = "/Users/genevievesavard/Data"
# local stack_root values that must become the cluster ts-PWS OUTPUT tree
LOCAL_STACK_ROOTS = [
    LOCAL_PROJ + "/riehen/stacks_tspws",
    LOCAL_PROJ + "/aargau/stacks_tspws",
    "/Volumes/T7blue/riehen-data/STACK_CHRI_normZ",
    "/Volumes/T7blue/aargau-data/STACK_CHAA_normZ",
    "/Volumes/Data/unige/hautesorne/STACK_coh_all",
]


def rewrite(text, net, a):
    """Path-only rewrite. Order matters: stack_root before the generic prefix swap."""
    tspws_tree = "%s/%s/stacks_tspws" % (a.proj, net)
    for old in LOCAL_STACK_ROOTS:
        text = re.sub(r'(stack_root:\s*)"%s"' % re.escape(old),
                      r'\1"%s"' % tspws_tree, text)
    text = text.replace(LOCAL_PROJ, a.proj)
    text = text.replace(LOCAL_NOISEPY, a.noisepy)
    text = text.replace(LOCAL_DATA, a.data)
    # Laptop paths surviving in COMMENTS are harmless to the picker but defeat
    # preflight.sh's "no /Users|/Volumes anywhere" check, which is worth keeping strict.
    for old, new in ((LOCAL_STACK_ROOTS[2], NETS["riehen"][1]),
                     (LOCAL_STACK_ROOTS[3], NETS["aargau"][1]),
                     (LOCAL_STACK_ROOTS[4], NETS["hautesorne"][1])):
        text = text.replace(old, new)
    text = re.sub(r"/Users/\S*?vbounds_\w+\.json",
                  "%s/%s/vbounds_%s.json" % (a.proj, net, net), text)
    return text


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--noisepy", default=CDFF + "/savardg/NoisePy-ant",
                    help="code root on the cluster")
    ap.add_argument("--proj", default=CDFF + "/savardg/extract_higher_modes/Projects",
                    help="output root on the cluster")
    ap.add_argument("--data", default=CDFF + "/savardg/data",
                    help="auxiliary data root (vsg_dir / shapefiles; UNUSED by "
                         "pick/QC/export, kept only so the configs stay loadable)")
    ap.add_argument("--nproc", type=int, default=32,
                    help="picker processes in the finalize job. MUST match the "
                         "--cpus-per-task you submit finalize with, or the extra cores "
                         "sit idle (the picker takes nproc from this YAML, not from "
                         "SLURM_CPUS_PER_TASK). Default 32.")
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)

    for net, (tmpl, src_root, code) in NETS.items():
        # ---- picker config -------------------------------------------------
        src = os.path.join(PARAM, tmpl)
        text = rewrite(open(src).read(), net, a)
        header = ("# GENERATED by cluster/make_cluster_configs.py -- do not hand-edit.\n"
                  "# Source template: param_files/%s\n"
                  "# Cluster: yggdrasil. stack_root is the ts-PWS OUTPUT tree built by\n"
                  "# 01_build_tspws.sbatch from the substacks at\n"
                  "#   %s\n\n" % (tmpl, src_root))
        p = os.path.join(OUT, "modesep_%s_tspws.yaml" % net)
        open(p, "w").write(header + text)
        print("wrote", os.path.relpath(p, PARAM))

        # ---- pipeline config -----------------------------------------------
        # riehen/aargau have a _tspws pipeline already; hautesorne only a pws one.
        ptmpl = "pipeline_%s_tspws.yaml" % net
        if not os.path.exists(os.path.join(PARAM, ptmpl)):
            ptmpl = "pipeline_%s.yaml" % net
        ptext = rewrite(open(os.path.join(PARAM, ptmpl)).read(), net, a)
        ptext = ptext.replace("picker_config: %s/param_files/modesep_%s_tspws.yaml"
                              % (a.noisepy, net),
                              "picker_config: %s/param_files/cluster/modesep_%s_tspws.yaml"
                              % (a.noisepy, net))
        ptext = ptext.replace("picker_config: %s/param_files/modesep_%s.yaml"
                              % (a.noisepy, net),
                              "picker_config: %s/param_files/cluster/modesep_%s_tspws.yaml"
                              % (a.noisepy, net))
        # Haute-Sorne's local pipeline predates the substack copy: force the production
        # stack method and the ts-PWS output tree/label so all three networks match.
        # Short-period fast-spray gate (user, 2026-07-31). fund/love only: at T<1 s their
        # fundamental branches sit at 1.0-1.8 km/s so >2 is spray, while the Rayleigh
        # OVERTONE legitimately runs 1.8-3.5 there (a blanket cut removes 26-29% of it).
        if "short_vmax:" not in ptext:
            ptext = re.sub(r"(\n\s*u_bin:[^\n]*\n)",
                           r"\1  short_vmax: ''   # DISABLED (user 2026-07-31: let the inversion fit the full\n"
                           r"                    # distribution; assess the lowest reliable period at the Vs stage).\n"
                           r"                    # Re-enable with fund=2.0,love=2.0 -- GROUP only, overtone exempt.\n"
                           r"  short_vmax_tmax: 1.0\n", ptext, count=1)
        ptext = re.sub(r"(\n\s*nproc:\s*)\d+",
                       r"\g<1>%d" % a.nproc, ptext, count=1)
        ptext = re.sub(r"(\n\s*stack:\s*)pws\b[^\n]*",
                       r"\1tspws                     # DISP_STACK -- wavelet-domain PWS "
                       r"(production; substacks now on the cluster)", ptext)
        ptext = ptext.replace("/dispersion_unified_vmin0.2\n",
                              "/dispersion_unified_vmin0.2_tspws\n")
        ptext = ptext.replace("/1_velocity_maps/inputs\n", "/1_velocity_maps/inputs_tspws\n")
        # Prefix the label unless it already is. A lookahead after \s* backtracks to a
        # zero-width match and fires anyway ("label:tspws_ tspws_..."), so capture the
        # value and decide on it explicitly.
        ptext = re.sub(r"\nlabel:[ \t]*(\S+)",
                       lambda m: "\nlabel: " + (m.group(1) if m.group(1).startswith("tspws_")
                                                else "tspws_" + m.group(1)),
                       ptext, count=1)
        # The picker measures group AND phase for every wave/mode, but one export pass
        # writes one measure. Append an export_phase block so the finalize stage ships
        # both. Phase velocities exceed group, hence the wider upper bounds.
        if "\nexport_phase:" not in ptext:
            ptext = ptext.rstrip("\n") + """

export_phase:                      # second export pass -- phase picks
  measure: phase
  period_axis: scale
  max_std: 0.2
  out_suffix: "_phase"
  vbounds: "fund=0.2:4.5,overtone=1.5:5.5,love=0.2:4.5"
"""
        q = os.path.join(OUT, "pipeline_%s_tspws.yaml" % net)
        open(q, "w").write("# GENERATED by cluster/make_cluster_configs.py -- "
                           "do not hand-edit.\n# Source template: param_files/%s\n\n"
                           % ptmpl + ptext)
        print("wrote", os.path.relpath(q, PARAM))


if __name__ == "__main__":
    main()
