#!/usr/bin/env python3
"""Generate the swtomotv velocity-map dataset YAMLs for the cluster ts-PWS production run.

Six files (group + phase x riehen/aargau/hautesorne) written to param_files/cluster/tomo/.
They differ from the laptop originals only in paths -- pick tables come from the ts-PWS
export directory (`inputs_tspws`), and the station file is `stations_all.csv`, generated by
build_station_file.py from the stack attrs.

Why stations_all.csv and not the existing stations.csv: the shipped lists are SHORT against
the current picks -- Aargau's has 150 stations where the picks reference 190, Riehen's 187
against 198. A station missing from the file makes its paths unusable, silently. Riehen has
a `stations_keepflag.csv` covering all 198 (the 2026-07-15 control run concluded the
misorientation exclusion should be dropped); Aargau never had an equivalent, hence the
generator. Verified: generated Riehen coordinates match stations_keepflag.csv to 0.2 m.

Grid settings are carried over from the 2026-07-24 fine-grid production run.

Usage:
  python make_tomo_configs.py [--proj PATH]
"""
import argparse
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "param_files", "cluster", "tomo")

# per network: (bounds, dx_km, lc_floor_km)
#   bounds/dx from the laptop production configs; lc floor from run_finegrid_maps.sh
#   (riehen 1.5 at dx 0.2, aargau 3.0 at dx 0.5). Haute-Sorne had no fine-grid production
#   run, so it inherits Aargau's floor as the same-dx analogue -- REVIEW before trusting it.
NETS = {
    "riehen":     ([47.500977, 47.666447, 7.534873, 7.777094], 0.2, 1.5),
    "aargau":     ([47.377852, 47.617948, 8.052090, 8.398219], 0.5, 3.0),
    "hautesorne": ([47.237194, 47.464396, 6.945514, 7.491476], 0.5, 3.0),
}
WAVES = ("fund", "overtone", "love")

TEMPLATE = """# GENERATED by cluster/make_tomo_configs.py -- do not hand-edit.
# swtomotv dataset: {net}, ts-PWS production picks ({measure}).
name: {name}
pick_files:
{picks}
station_file: {inputs}/stations_all.csv
output_root: {proj}/{net}/tomo/1_velocity_maps/production/tspws_{outtag}_dx{dx}{lctag}
bounds: [{bounds}]
dx_km: {dx}
# The picks are measured ON the CWT scale ladder (uneven, ~5.95% steps), so file names and
# the stored `period` must carry the real rung. swtomotv defaults period_decimals=1, which
# labelled the T=2.153 s rung as "2.1" -- 11 of 36 Riehen periods were then >1% off, worst
# 2.6%. Its own config comment recommends 3 for scale-native datasets. No collisions occur
# at 1 decimal for these networks, so nothing was overwritten -- only mislabelled.
period_decimals: 3
filters:
  fund:     [100.0, 1]
  overtone: [100.0, 1]
  love:     [100.0, 1]
two_step:
  fund: false
  overtone: false
  love: false
columns: {{}}
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--proj", default="/home/users/s/savardg/extract_higher_modes/Projects")
    ap.add_argument("--tag", default="",
                    help="suffix for the output_root AND the config file name, so a "
                         "smoothing experiment lands BESIDE the production maps instead of "
                         "overwriting them (e.g. _lc0.5, _lcfix1). Empty = production.")
    ap.add_argument("--inputs-name", default="inputs_tspws",
                    help="directory under tomo/1_velocity_maps/ holding the pick tables and "
                         "stations_all.csv. Override to point a run at a FILTERED pick tree "
                         "(e.g. inputs_tspws_histfilt) without touching the production one.")
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)

    for net, (bounds, dx, lc) in NETS.items():
        inputs = "%s/%s/tomo/1_velocity_maps/%s" % (a.proj, net, a.inputs_name)
        for measure, suffix in (("group", ""), ("phase", "_phase")):
          for cd in ("measured", "blanket", "scaled"):
            picks = "\n".join(
                "  %-9s %s/picks_%s_uni%s.csv"
                % (w + ":", inputs, "overtone" if w == "overtone" else w, suffix)
                for w in WAVES)
            txt = TEMPLATE.format(
                net=net, measure="%s (Cd: %s)" % (measure, cd),
                name="%s_tspws_%s_%s_dx%s" % (net, measure, cd, dx),
                picks=picks, inputs=inputs, proj=a.proj, dx=dx,
                outtag="%s_%s" % (measure, cd),
                lctag=a.tag,
                bounds=", ".join("%.6f" % b for b in bounds))
            q = os.path.join(OUT, "%s_tspws_%s_%s%s.yaml" % (net, measure, cd, a.tag))
            open(q, "w").write(txt)
            print("wrote", os.path.basename(q), "| lc %.1f km, dx %.1f km" % (lc, dx))


if __name__ == "__main__":
    main()
